return {
 Weapons = {
  {name='M1911',clip=8,reserve=80,damage=25,delay=.28,reload=1.2,cost=0,automatic=false},
  {name='M1 Carbine',clip=15,reserve=120,damage=65,delay=.4,reload=1.8,cost=1000,automatic=false},
  {name='Pump Shotgun',clip=6,reserve=48,damage=35,pellets=6,delay=.85,reload=2.2,cost=1500,automatic=false},
  {name='Thompson',clip=30,reserve=180,damage=38,delay=.15,reload=1.9,cost=1800,automatic=true},
  {name='Ray Gun',clip=20,reserve=120,damage=220,delay=.2,reload=2.3,cost=0,automatic=true},
  {name='Thundergun',clip=2,reserve=10,damage=600,delay=1.2,reload=2.5,cost=0,automatic=false},
 },
 FloorY=80, MaxActiveZombies=18,
}
